packages:
  - cli
  - compiler
  - packages
  - tools/vscode-extension
  - tools/chrome-extension
  - "benchmarks/performance"
  - "benchmarks/performance/implementations/*"

onlyBuiltDependencies:
  - esbuild
