package nodes

import (
	"fmt"
	"strings"

	"hudson-newey/2web/src/content/document/documentErrors"
	"hudson-newey/2web/src/content/page"
	"hudson-newey/2web/src/models"
)

// CompileFunctionCalls compiles the event reducers that directly call a
// function: an imported server function (rpc call) or a function declared in
// one of the page's compiled script blocks.
//
// e.g. with 'import { greet } from "./api/users.server.ts";' in the page's
// compiled script, the binding:
//
//	@click="greet($name)"
//
// compiles into a standalone event listener that calls the client side rpc
// passthrough (generated by the import, see scriptImportNode) with the
// reactive variables in the call arguments resolved to their runtime values.
// A function that was declared in a compiled script block is called the same
// way (its declaration lives in the same shared reactive runtime scope, see
// twoScriptNode).
//
// Assignment reducers are compiled by the variable they assign to (see
// reactiveVariableNode) and are skipped here.
//
// It must run after the page AST has been walked (so that every server import
// has registered its rpc functions) and before the page's reactive runtime is
// emitted (so that the listeners are included in the shared reactive runtime
// script).
func CompileFunctionCalls(pageModel *page.Page, index *ReactiveIndex) {
	pageContent := pageModel.Html.Content
	compiled := false

	for _, event := range index.Events {
		if event.node.assignmentSink != "" {
			continue
		}

		callTarget := callTargetOf(event.node.assignmentExpr)

		if !index.HasRpcFunction(callTarget) && !index.HasCompiledFunction(callTarget) {
			callError := models.NewError(
				fmt.Sprintf(
					"event '%s' calls the function '%s', which is neither declared in a compiled script block nor imported from a server script. Server functions are imported with 'import { %s } from \"path.server.ts\";'",
					event.node.eventName, callTarget, callTarget,
				),
				pageModel.InputPath,
				event.node.position,
			)

			documentErrors.AddErrors(&callError)
			continue
		}

		call := resolveCallArguments(event.node.assignmentExpr, index)

		elementSelector := pageModel.Ids.CreateElementName()
		pageContent = strings.ReplaceAll(pageContent, event.node.selector(), elementSelector)

		listener := fmt.Sprintf(
			`document.querySelector("[%s]").addEventListener("%s", async () => { await %s; });`,
			elementSelector, event.node.eventName, call,
		)

		// The dependencies ensure that the runtime variables referenced by the
		// call arguments are declared before this listener (ordering only;
		// the listener body itself runs on the event).
		pageModel.AppendReactiveRuntime(page.ReactiveRuntimeChunk{
			Variable:     "rpcCall:" + elementSelector,
			Dependencies: event.dependencies,
			Content:      listener,
		})

		compiled = true
	}

	if compiled {
		pageModel.SetContent(pageContent)
	}
}

// callTargetOf returns the identifier of the function that a call expression
// calls, or an empty string when the expression isn't a bare function call.
func callTargetOf(call string) string {
	open := strings.Index(call, "(")

	if open <= 0 {
		return ""
	}

	return strings.TrimSpace(call[:open])
}

// resolveCallArguments substitutes the reactive variables referenced in a
// call expression with their runtime representations.
//
// A variable that has a runtime representation (it is assigned by events or
// computed from at runtime) is replaced with its runtime variable name. A
// static variable is replaced with its resolved initial expression, so the
// call arguments are inlined with the same value the rest of the page renders.
func resolveCallArguments(call string, index *ReactiveIndex) string {
	for _, variable := range index.Variables {
		if !containsSelector(call, variable.selector()) {
			continue
		}

		if runtimeName := index.RuntimeVariableName(variable.selector()); runtimeName != "" {
			call = replaceSelector(call, variable.selector(), runtimeName)
			continue
		}

		resolved, ok := index.ResolveExpression(variable)
		if !ok {
			// The variable is part of a cyclic dependency, which is reported
			// as a compiler error elsewhere. Leave the selector unreplaced
			// rather than emitting a broken call.
			continue
		}

		call = replaceSelector(call, variable.selector(), "("+resolved+")")
	}

	return call
}
